### ISSUE TITLE
Intercom error when pressing the back button. Shutting down VM

### ISSUE THREAD

**Issue by orodrigue12** [deepak786/intercom_flutter#100]
DecorView@15ef58e[MainActivity]
D/AndroidRuntime( 8635): Shutting down VM
E/AndroidRuntime( 8635): FATAL EXCEPTION: main
E/AndroidRuntime( 8635): Process: com.android.app, PID: 8635
E/AndroidRuntime( 8635): java.lang.RuntimeException: Unable to destroy activity {com.android.app/com.android.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4589)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4611)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
E/AndroidRuntime( 8635): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8635): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.main(ActivityThread.java:6819)
E/AndroidRuntime( 8635): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8635): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime( 8635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
E/AndroidRuntime( 8635): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 8635): 	at io.maido.intercom.IntercomFlutterPlugin.onDetachedFromEngine(IntercomFlutterPlugin.kt:209)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:262)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:278)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:122)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:555)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:589)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:610)
E/AndroidRuntime( 8635): 	at android.app.Activity.performDestroy(Activity.java:7395)
E/AndroidRuntime( 8635): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4574)
E/AndroidRuntime( 8635): 	... 11 more
Lost connection to device.
Exited (sigterm)

**Comment by benjwilson10** [comment]
Exactly the same error when pressing the Android back arrow

D/AndroidRuntime( 7138): Shutting down VM
E/AndroidRuntime( 7138): FATAL EXCEPTION: main
E/AndroidRuntime( 7138): Process: fit.withu.flutter.withu, PID: 7138
E/AndroidRuntime( 7138): java.lang.RuntimeException: Unable to destroy activity {fit.withu.flutter.withu/fit.withu.flutter.withu.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 7138): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
E/AndroidRuntime( 7138): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
E/AndroidRuntime( 7138): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime( 7138): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
E/AndroidRuntime( 7138): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 7138): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 7138): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 7138): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7138): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 7138): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 7138): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 7138): 	at io.maido.intercom.IntercomFlutterPlugin.onDetachedFromEngine(IntercomFlutterPlugin.kt:209)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:268)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:112)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:528)
E/AndroidRuntime( 7138): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime( 7138): 	at android.app.Activity.performDestroy(Activity.java:7522)
E/AndroidRuntime( 7138): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
E/AndroidRuntime( 7138): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)
E/AndroidRuntime( 7138): 	... 9 more
I/System.out( 7138): (HTTPLog)-Static: isSBSettingEnabled false
I/BranchSDK( 7138): returned {}
I/System.out( 7138): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 7138): (HTTPLog)-Static: isSBSettingEnabled false
Lost connection to device.
Exited (sigterm)
