### ISSUE TITLE
User is not getting bound to existing intercom user.

### ISSUE THREAD

**Issue by Defuera** [deepak786/intercom_flutter#143]
Hi, I'm integrating intercom into flutter application and need to make sure existing users (registered through web) will be able to continue conversation on mobile device.

Is it possible?

If yes, please help me resolve the issue. I'm getting intercom id from our backend and then register user like this:

```

    await Intercom.initialize(
      app_id,
      androidApiKey: androidAccessToken,
      iosApiKey: iosAccessToken,
    );

    final hmacSha256 = Hmac(sha256, utf8.encode(verificationKey));
    final digest = hmacSha256.convert(utf8.encode(intercomId));
    final hash = hex.encode(digest.bytes);

    await Intercom.setUserHash(hash);
    await Intercom.registerIdentifiedUser(userId: intercomId);
```

I am able to register user successfully, can send messages and see them in admin portal.
**But** those messages are visible for a new user, not the user I am expecting to see.

For example: 
I get id from server : `609f09dd114f5b7022dd26dd`
When I send a message from this user, I expect to be able to communicate to him via  portal here https://app.intercom.com/a/apps/dpgx0jar/users/609f09dd114f5b7022dd26dd/

But instead it appears in portal as https://app.intercom.com/a/apps/dpgx0jar/users/609fb322586cbe6b6ae9f18d/

![image](https://user-images.githubusercontent.com/1181883/118653948-57e73d00-b7e8-11eb-85c4-12edd65dce3c.png)

**Comment by deepak786** [comment]
```
final digest = hmacSha256.convert(utf8.encode(intercomId));
await Intercom.registerIdentifiedUser(userId: intercomId);
```

In the above code, you have used the `intercomId` as userId. Make sure it is the userId of the user from your server and it is the same userId by which you have register the user in Intercom from the web.

Suppose userId from your server is `609f09dd114f5b7022dd26dd`

Passing the `609f09dd114f5b7022dd26dd ` will register the user in the Intercom with user_id equalTo `609f09dd114f5b7022dd26dd ` and then Intercom will create a new id for its own record for e.g: `609fb322586cbe6b6ae9f18d`

**_Note: Register the user in Intercom from both Mobile or Web platforms with the same userId or email. Otherwise, it will end up having a new user in Intercom._**

**Comment by Defuera** [comment]
Issue is solved! Thanks so much for elaborated reply! 🙏 🙏 🙏

**Comment by deepak786** [comment]
don't hesitate to buy me a coffee.
https://www.buymeacoffee.com/deepakdroid
