### ISSUE TITLE
When click on close icon, NOT CLOASED !

### ISSUE THREAD

**Issue by Shatha-Naami** [deepak786/intercom_flutter#208]
if the intercom displays messenger then tries user to close it, does not close ?? **" only on android"**

intercom_flutter: ^6.0.0 (version of intercom)
![intercom](https://user-images.githubusercontent.com/60509531/151617744-460b67c0-1e5e-4f61-b8b8-6a8f6b353ebb.png)

**Comment by deepak786** [comment]
seems to be a similar issue as https://github.com/v3rm0n/intercom_flutter/issues/203

I will send a message to Intercom support.
@Shatha-Naami could you please do the same as well?

**Comment by Shatha-Naami** [comment]
@deepak786 
okay, I will send it to Intercom support!
But I think not the best solution to wrap the intercom view then use

 Intercom.hideMessenger()

**Comment by deepak786** [comment]
They said this issue was resolved in the [10.4.1 version](https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md#version-1041).
In the latest `intercom_flutter: 6.0.0` we are using the SDK version `10.6.1`. So please make sure you are using the updated SDK version.

If you still have an issue with the latest SDK, please let me know.
