### ISSUE TITLE
iOS messager won't work if enforce-indentity-verification is enabled

### ISSUE THREAD

**Issue by idy** [deepak786/intercom_flutter#210]
### Dependencies:
intercom_flutter package dependency:
```
flutter_intercom: ^6.0.0
```
podfile.lock intercom related package versions:
```
  - Intercom (11.0.1)
  - intercom_flutter (5.0.0):
    - Flutter
    - Intercom (~> 11.0.1)
```

#### source code fragment
```dart
    final hash = await api.user.intercomHash();
    await Intercom.setUserHash(hash);
    await Intercom.registerIdentifiedUser(userId: FirebaseAuth.instance.currentUser!.uid);
    await Intercom.displayMessenger();
```

The hash calculated from the function is the same as the `online calculator` on intercom documentation.

#### want
the messager opened and ready to talk.
#### got
error logs:
```
[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error (401) - Request failed: unauthorized (401)
```
screen shot:
![WechatIMG8](https://user-images.githubusercontent.com/687349/152958039-839a9f6c-0df4-4dcd-a146-6d78e3df791a.jpeg)

**Comment by deepak786** [comment]
@idy it seems that the hash is not correct. That's why the request is unauthorized.
Please follow this code to generate the hash in dart
https://gist.github.com/thewheat/7342c76ade46e7322c3e?permalink_comment_id=3911002#gistcomment-3911002

here the __DATA__ must be the userId.

If possible please share the sample code that reproduces the issue.

**Comment by deepak786** [comment]
@idy do you still have the issue?
