### ISSUE TITLE
Push Notification for iOS

### ISSUE THREAD

**Issue by nihalreddy33** [deepak786/intercom_flutter#29]
How to configure push notifications for iOS?

**Comment by zeucxb** [comment]
@nihalreddy33 do u found something? Does this support push notification?

**Comment by Spikes042** [comment]
Push Notifications hasn't been implemented on iOS yet, only Android (#27)

**Comment by Zeissus** [comment]
This is very much needed!

**Comment by edyonil** [comment]
What is required to add support for this functionality?

**Comment by gabdsg** [comment]
Any update?

**Comment by Zazo032** [comment]
> What is required to add support for this functionality?

For the plugin to support the iOS side of this feature, it has to be developed using Platform Channels, as almost every other feature in the plugin. You can see past commits as reference on how to do it. Feel free to submit a PR with the implementation of this feature, it would be much appreciated.

**Comment by pawlowskim** [comment]
I did some tests today. I have working FCM set up already and I wanted to add intercom push notifications as well. 
So I have added proper method to iOS part of the plugin to register token. But I have realised, that Intercom needs `NSData` which is returned from ``didRegisterForRemoteNotificationsWithDeviceToken`` instead of a ``NSString`` (working token from FCM). 
I have found some code (that I don't understand to be honest) in iOS implementation for react-native-intercom that takes FCM token and create proper data to register for Intercom lib (https://github.com/tinycreative/react-native-intercom/blob/master/iOS/IntercomWrapper.m#L202). But it doesn't help. So I tried directly register token in my native part. After small change I was able to receive notifications from Intercom. I didn't test it properly since I don't have time ATM. Maybe in next 2-4 weeks I will post again when I actually start working on this feature again. 

How to receive push notifications for iOS (if you have login feature in the app this is not the best solution probably. But as I said, I didn't test it properly).
1. Proper certs was set up in Intercom:
 https://i.ibb.co/hYkddsW/Screenshot-2019-11-08-at-10-43-24.png
2. I needed to update `` AppDelegate.swift``
```
import Intercom

override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Intercom.setDeviceToken(deviceToken)
    }
```
3. Not sure if it's important but I have also added ``IntercomAutoIntegratePushNotifications`` set to ``YES`` for my ``Info.plist`` file.


PS. Snippet for flutter obj-c type projects ``AppDelegate.m``
```
#import <Intercom/Intercom.h>

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [Intercom setDeviceToken:deviceToken];
}
```

**Comment by masashi-sutou** [comment]
I would also like to be able to push iOS notifications from this package, but you can do the same with intercom webhook topic and firebase cloud functions. 

## Suggest a workaround

It is possible to send push notifications by deploying a function that triggers `conversation.admin.single.created` and `conversation.admin.replied` to firebase cloud functions and fetch user's fcm token stored in firestore from intercom user_id.

### intercom webhook topic 

- https://developers.intercom.com/building-apps/docs/webhook-model#section-webhook-topics

### User Model for intercom Webhook topic response body

- https://developers.intercom.com/building-apps/docs/webhook-model#section-user-tag-model-for-webhooks
- but latest version (1.4.0) is a little different request body.
- I get intercom user_id by `request.body.item.user.user_id`.

### sample code

- https://github.com/intercom-archive/intercom-webhooks/blob/master/node/index.js

**Comment by pawlowskim** [comment]
@masashi-sutou Thanks! I will check it out.

**Comment by pawlowskim** [comment]
@masashi-sutou Thanks!!! Your workaround works. There are little bit more code for getting admin name for new conversations since it's not sent with the hook message, but It's doable to get using their SDK.

**Comment by gabdsg** [comment]
> ```
> import Intercom
> 
> override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
>         Intercom.setDeviceToken(deviceToken)
>     }
> ```

This worked for me

**Comment by pawlowskim** [comment]
@gabdsg Yes, it works, but when you have login feature in the app, you might want to no logged in users have possibility to communicate through Intercom. So you need to write flutter plugin (or extend Intercom flutter plugin) to register / unregister device token on demand.

**Comment by pawlowskim** [comment]
I have created a PR with implementation for iOS. Until it's approved, you can test it from my repo: https://github.com/pawlowskim/intercom_flutter

**Comment by UnderscoreShift** [comment]
Let me necro this with a solution that seems to be working with Flutter 2.2.0 (Dart 2.13.0) and intercom_flutter 3.2.1:


1. In your Info.plist file (or files if you use multiple) set `IntercomAutoIntegratePushNotifications` to `NO` to manually manage notifications
2. Make sure you use `Intercom.sendTokenToIntercom(token)` after `Intercom.registerIdentifiedUser(userId: userId)`
3. Here is where I'm skeptical: in your `AppDelegate.swift` `import Intercom` at the top and under `@objc class AppDelegate: FlutterAppDelegate {` add the following:
```
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Intercom.setDeviceToken(deviceToken)
}
```

You should have something like this:
```
imports
...
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  <the_override_from_above>
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
...
```
With this, I think that the Intercom notifications will just be managed by Firebase's background setup; this includes the icon too.

It's still a work in progress, Intercom and regular Firebase notifications work, the flavors (controlled by the second override func) are set up correctly and this library behaves as it should when I open it and the app.

Some feedback on this will be appreciated, thanks!

**Comment by deepak786** [comment]
new version `intercom_flutter: 4.0.0` is released which will solve the issue of the iOS notifications.
Just follow the below steps with version 4.0.0
1. In your Info.plist file set `IntercomAutoIntegratePushNotifications` to `NO` to manually manage notifications.
2. Send your APNS token to Intercom with `Intercom.sendTokenToIntercom(yourAPNSToken)`

closing this issue. If you still have an issue then feel free to create a new issue.
