### ISSUE TITLE
Can not click or make other gestures with unread message group

### ISSUE THREAD

**Issue by mesaigor** [deepak786/intercom_flutter#351]
Hi everyone,

We have a type of message sended by my intercom account that all users are receiving. When this users not read this messages, the intercom sdk creates and show a stack of messages for the user. This stack of messages can not be clicked or swiped to remove. This only happens on the message stack, if only one message is unread all functions works.

Anyone are passing by this issues?

**Comment by irbp** [comment]
Hi!

By default, the `MainActivity` in the Android project extends the `FlutterActivity` class. However, when I replaced `FlutterActivity` with `FlutterFragmentActivity`, the problem no longer persisted, and the messages became interactive, allowing both touch and gestures. It's likely that the Intercom native SDK relies on components that require `FragmentActivity`, which is why the substitution was necessary.

It might be a good idea for the package author to add this observation to the README, as it could be helpful for others encountering the same problem.

**Comment by deepak786** [comment]
I will talk to Intercom support engineers about this issue.

**Comment by deepak786** [comment]
What is the intercom_flutter version used?

**Comment by mesaigor** [comment]
We are using version 7.8.2

**Comment by deepak786** [comment]
I checked with Intercom support and they said that 
**This issue has already been reported internally. Not sure when we’ll have a fix for it as other things are a slightly higher priority.**

You can also contact Intercom customer support for more information.

**Comment by deepak786** [comment]
@Br1an-Boyle I received some messages regarding this issue and it seems that Intercom customer support is saying that this is an issue in intercom_flutter itself. They say they don't have a similar issue logged from anyone and asking to talk to intercom_flutter developers.

Could you please clarify?

**Comment by theVinesh** [comment]
Hello 👋 
As @irbp previously mentioned using `FlutterFragmentActivity` solves this issue. It's probably better to add this as part of the docs to advise the plugin users to extend `FlutterFragmentActivity` instead of `FlutterActivity`

Intercom's native android docs should highlight this too. I'll raise this with the team internally.
