### ISSUE TITLE
Upgrade to version 6 of intercom SDK

### ISSUE THREAD

**Issue by masashi-sutou** [deepak786/intercom_flutter#53]
I received email from intercom team.

> To continue to provide all Intercom users with a fast and secure mobile experience, we are deprecating version 5 and below of the Intercom mobile SDKs. Starting June 30th 2020, version 5 and below of the iOS and Android SDKs will no longer be supported, and will no longer work on your site. To continue to use Intercom in your apps, please upgrade to version 6 of the mobile SDKs. Version 6 supports Android API level 21 and iOS 10 and above. 

Will this package update the intercom SDK?

- https://github.com/v3rm0n/intercom_flutter/blob/master/ios/intercom_flutter.podspec#L20
- https://github.com/v3rm0n/intercom_flutter/blob/master/android/build.gradle#L44

**Comment by Zazo032** [comment]
I'll try to land a PR to bump the version next week.

**Comment by Zazo032** [comment]
Version `2.1.0` will land this week when https://github.com/v3rm0n/intercom_flutter/pull/54 is merged with support for Intercom SDK 6. Note that this version bump will require your app to bump minimum Android and iOS versions, otherwise, it won't work (this is a new requirement by the Intercom SDK).
