### ISSUE TITLE
env: sh\r: No such file or directory on flutter build

### ISSUE THREAD

**Issue by annegreenwood** [deepak786/intercom_flutter#99]
**Flutter doctor -v:**

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-BR)
    • Flutter version 1.22.2 at /Users/anne/development/flutter
    • Framework revision 84f3d28555 (7 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/anne/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/anne/Library/Android/sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.2

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 2 categories.
```
**Issue:**

Running flutter build apk or flutter build appbundle results in:

```
Building plugin intercom_flutter...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.0s

env: sh\r: No such file or directory


The plugin intercom_flutter could not be built due to the issue above.
```

Plugin version is 2.3.1.

**Comment by Zazo032** [comment]
Could you post the output of `flutter build appbundle -v`? That error log isn't very helpful

**Comment by annegreenwood** [comment]
Ok, so the output is too long, so I'm posting only the ones after that command triggers `assembleAarRelease` for intercom_flutter. Let me know if that's still not helpful.

```
[        ] Building plugin intercom_flutter...
[   +3 ms] Running Gradle task 'assembleAarRelease'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /Users/anne/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-2.3.1/android/gradlew.
[        ] /Users/anne/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-2.3.1/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/anne/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-2.3.1/android/]
/Users/anne/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-2.3.1/android/gradlew
-I=/Users/anne/development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/anne/development/flutter
-Poutput-dir=/Users/anne/Desktop/MyCompany/myproject/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true
-Pfont-subset=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[  +80 ms] env: sh\r: No such file or directory
[        ] Running Gradle task 'assembleAarRelease'... (completed in 0.1s)
[   +1 ms] env: sh\r: No such file or directory
           
[   +9 ms] "flutter appbundle" took 119,920ms.
[   +7 ms] The plugin intercom_flutter could not be built due to the issue above.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:848:7)
           #2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #3      _rootRunBinary (dart:async/zone.dart:1214:47)
           #4      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #5      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #8      Future._completeError (dart:async/future_impl.dart:537:5)
           #9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #19     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
           #20     _rootRunUnary (dart:async/zone.dart:1198:47)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #28     _run (package:flutter_tools/src/base/error_handling_io.dart)
           #29     _rootRunUnary (dart:async/zone.dart:1198:47)
           #30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #31     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #33     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #34     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #35     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
           #36     _rootRunUnary (dart:async/zone.dart:1198:47)
           #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #43     _rootRun (dart:async/zone.dart:1190:13)
           #44     _CustomZone.run (dart:async/zone.dart:1093:19)
           #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +256 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

I should add that the reason why flutter build is triggering assembleAarRelease is because a plugin I use has some issues with ProGuard, but it's had them for 3 releases in which I've already been using intercom and that wasn't an issue. Could that be the cause? The other plugins have logs like the one below, so they work:

```
[        ] Building plugin flutter_inappwebview...
[   +3 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/anne/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/android/gradlew.
[        ] /Users/anne/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/anne/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/android/]
/Users/anne/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/android/gradlew
-I=/Users/anne/development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/anne/development/flutter
-Poutput-dir=/Users/anne/Desktop/CargoSense/qrsensor_mobile/qrsensor_mobile/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true
-Pfont-subset=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+3179 ms] 
                    > Configure project :
                    WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
                    It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

                    > Task :assembleAarRelease UP-TO-DATE
                    > Task :preBuild UP-TO-DATE
                    > Task :extractProguardFiles UP-TO-DATE
                    > Task :preReleaseBuild UP-TO-DATE
                    > Task :mergeReleaseJniLibFolders UP-TO-DATE
                    > Task :mergeReleaseNativeLibs UP-TO-DATE
                    > Task :stripReleaseDebugSymbols UP-TO-DATE
                    > Task :copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
                    > Task :compileReleaseAidl NO-SOURCE
                    > Task :generateReleaseBuildConfig UP-TO-DATE
                    > Task :compileReleaseRenderscript NO-SOURCE
                    > Task :generateReleaseResValues UP-TO-DATE
                    > Task :generateReleaseResources UP-TO-DATE
                    > Task :packageReleaseResources UP-TO-DATE
                    > Task :parseReleaseLocalResources UP-TO-DATE
                    > Task :processReleaseManifest UP-TO-DATE
                    > Task :generateReleaseRFile UP-TO-DATE
                    > Task :javaPreCompileRelease UP-TO-DATE
                    > Task :compileReleaseJavaWithJavac UP-TO-DATE
                    > Task :extractReleaseAnnotations UP-TO-DATE
                    > Task :mergeReleaseGeneratedProguardFiles UP-TO-DATE
                    > Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
                    > Task :mergeReleaseShaders UP-TO-DATE
                    > Task :compileReleaseShaders UP-TO-DATE
                    > Task :generateReleaseAssets UP-TO-DATE
                    > Task :packageReleaseAssets UP-TO-DATE
                    > Task :packageReleaseRenderscript NO-SOURCE
                    > Task :prepareLintJarForPublish UP-TO-DATE
                    > Task :generateReleaseLibraryProguardRules UP-TO-DATE
                    > Task :processReleaseJavaRes NO-SOURCE
                    > Task :mergeReleaseJavaResource UP-TO-DATE
                    > Task :minifyReleaseWithR8 UP-TO-DATE
                    > Task :syncReleaseLibJars UP-TO-DATE
                    > Task :bundleReleaseAar UP-TO-DATE
                    > Task :uploadArchives

                    BUILD SUCCESSFUL in 3s
                    26 actionable tasks: 1 executed, 25 up-to-date
```

**Comment by Zazo032** [comment]
Logs still don't seem to be helpful.

Let's try two different things:

1. Does this also happen on `beta`, `dev` or `master` channels? (`flutter channel beta` + `flutter upgrade`)
1. You can try downgrading some of the versions that got updated with 2.3.1 and see if that helps. Do you know how to locally edit a plugin?
Possible culprits:
[Android Gradle plugin](https://github.com/v3rm0n/intercom_flutter/pull/97/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aL12-R12)
[Gradle wrapper](https://github.com/v3rm0n/intercom_flutter/pull/97/files#diff-4c5ffadbdf6016477a1c3768e0b7381cc298bd558b1784871f407cbcb0efacceL6-R6)

**Comment by willladislaw** [comment]
I ran `gradle ...` instead of `gradlew ...` inside the Android Dir, which then triggered a gradle upgrade (downloaded a bunch of gradle related stuff) now I have the same issue.  

Error

[ +1 ms] env: sh\r: No such file or directory

[ +10 ms] Exception: The plugin admob_flutter could not be built due to the issue above.
[ +4 ms]
#0 throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)

#2 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#3 _rootRunUnary (dart:async/zone.dart:1198:47)
#4 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5 _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7 Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8 Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11 RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12 _rootRunUnary (dart:async/zone.dart:1198:47)
#13 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14 _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16 Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17 Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20 AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21 _rootRunUnary (dart:async/zone.dart:1198:47)
#22 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23 _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#25 Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#26 Future._completeWithValue (dart:async/future_impl.dart:529:5)
#27 Future._asyncCompleteWithValue. (dart:async/future_impl.dart:567:7)
#28 _rootRun (dart:async/zone.dart:1190:13)
#29 _CustomZone.run (dart:async/zone.dart:1093:19)
#30 _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#31 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037:23)
#32 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by willladislaw** [comment]
[+34039 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]      /Users/will/.gradle/caches/transforms-2/files-2.1/dcdc98f5202138eb83b2d992b19de2af/play-services-ads-lite-19.6.0/AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 36s
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"0","progressId":null,"finished":true}}]
[ +421 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +7 ms] Building plugin admob_flutter...
Running Gradle task 'assembleAarRelease'...
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"1","progressId":null,"message":"Running Gradle task 'assembleAarRelease'..."}}]
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew.
[        ] /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/] /Users/will/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-1.0.1/android/gradlew -I=/Users/will/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/will/flutter -Poutput-dir=/Users/will/flutter_workspace/projectx/build/app -Pis-plugin=true -PbuildNumber=1.0 -q -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[  +24 ms] env: sh\r: No such file or directory
[{"event":"app.progress","params":{"appId":"99583fca-ff91-439d-81be-cb9e58bc5344","id":"1","progressId":null,"finished":true}}]
[   +1 ms] env: sh\r: No such file or directory

[   +5 ms] Exception: The plugin admob_flutter could not be built due to the issue above.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
